name: roadize
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  flutter_svg: ^0.19.1
  fl_chart: ^0.12.2
  date_format: ^1.0.9 #https://pub.dev/packages/date_format/install
  intl: ^0.16.1 #https://pub.dev/packages/intl
  animations: ^1.1.2 #https://pub.dev/packages/animations
  bottom_bar_line: ^0.1.1 #https://pub.dev/packages/bottom_bar_line
  flutter_simple_rating_bar: 0.0.3 #https://pub.dev/packages/flutter_simple_rating_bar/install
  flutter_rating_bar: ^3.2.0+1 #https://pub.dev/packages/flutter_rating_bar
  mysql1: ^0.17.1 #https://pub.dev/packages/mysql1
  provider: ^4.3.2+4 #https://pub.dev/packages/provider
  password: ^1.0.0 #https://pub.dev/packages/password
  photo_manager: ^0.5.8 #https://pub.dev/packages/photo_manager


  firebase_auth: ^0.20.0+1
  firebase_core: ^0.7.0
  cloud_firestore: ^0.16.0
  google_sign_in: ^4.5.9
  firebase_storage: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - images/
    - images/icons/
    -
  fonts:
    - family: nexon_light
      fonts:
        - asset: fonts/nexon_light.otf
    - family: nexon2_light
      fonts:
        - asset: fonts/nexon2_light.otf
    - family: nexon_medium
      fonts:
        - asset: fonts/nexon_medium.ttf